services:
    db:
        hostname: db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - C:\docker\jokesdb:/var/lib/mysql
        ports:
            - 3307:3306
    jokes-service:
        hostname: jokesservice
        build: ./Buffoon
        environment:
            spring.datasource.username: root
            spring.datasource.password: password
            spring.datasource.url: jdbc:mysql://db:3306/spring_app
        ports:
            - 8080:8080
    ratings-service:
        hostname: ratingsservice
        build: ./Jokes Rating Service
        ports:
            - 8081:8081
        environment:
            JOKE_SERVICE_BASE_URL: http://jokesservice:8080
            spring.datasource.username: root
            spring.datasource.password: password
            spring.datasource.url: jdbc:mysql://db:3306/ratings_service
            server.port: 8081
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq
        volumes:
            - C:\docker\rabbitmq\data:/var/lib/rabbitmq/
            - C:\docker\rabbitmq\etc:/etc/rabbitmq/
            - C:\docker\rabbitmq\logs:/var/log/rabbitmq/
