services:
    nginx:
        image: nginx
        volumes:
            - ./Frontend/buffoon/build:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        # ports:
        #     - 80:80
        #     - 443:443
        depends_on:
            - frontend
    db:
        hostname: db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ~/docker/jokes-application/mysql:/var/lib/mysql
        # ports:
        #     - 3307:3306
    userdb:
        hostname: userdb
        image: mongo
        volumes:
            - ~/docker/jokes-application/mongo:/data/db
        # ports: 
        #     - 27018:27017
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq
        # ports: 
        #     - 15691:15691
        #     - 15692:15692
        #     - 25672:25672
        #     - 4369:4369
        #     - 5671:5671
        #     - 5672:5672
        # volumes:
        #     - ~/docker/jokes-application/rabbitmq/etc:/etc/rabbitmq/
        #     - ~/docker/jokes-application/rabbitmq/logs:/var/log/rabbitmq/
        #     - ~/docker/jokes-application/rabbitmq/data:/var/lib/rabbitmq/
    jokes-service:
        hostname: jokesservice
        build: ./JokeService
        environment:
            spring.datasource.username: root
            spring.datasource.password: password
            spring.datasource.url: jdbc:mysql://db:3306/jokes_service
            spring.rabbitmq.host: rabbitmq
        # ports:
        #     - 8080:8080
    ratings-service:
        hostname: ratingsservice
        build: ./RatingService
        # ports:
        #     - 8081:8081
        environment:
            JOKE_SERVICE_BASE_URL: http://jokesservice:8080
            spring.datasource.username: root
            spring.datasource.password: password
            spring.datasource.url: jdbc:mysql://db:3306/ratings_service
            server.port: 8081
            spring.rabbitmq.host: rabbitmq
    user-service:
        hostname: userservice
        build: ./UserService
        environment: 
            - PORT=8082
            - DB_URI=mongodb://userdb:27017
        # ports:
        #     - 8082:8082
    frontend:
        hostname: frontend
        build: ./Frontend
        # ports: 
        #     - 4000:5000
    backed:
        build: ./BackedFront
        hostname: backedfront
        environment: 
            - PORT=8083
            - JOKE_SERVICE_BASE=http://jokesservice:8080
            - RATING_SERVICE_BASE=http://ratingsservice:8081
            - USER_SERVICE_BASE=http://userservice:8082
        ports:
            - 8083:8083
